services:
  fnpackup:
    image: snltty/fnpackup:{version}
    container_name: fnpackup
    privileged: true
    network_mode: host
    restart: always
    tty: true
    stdin_open: true
    volumes:
      - "/${TRIM_APPDEST_VOL}/@appshare/fnpackup-docker/projects:/app/projects"
      - "/${TRIM_APPDEST_VOL}/@appshare/fnpackup-docker/statics:/app/statics"
      - "/usr/local/bin/appcenter-cli:/app/appcenter-cli"
      - "/usr/local/bin/fnpack:/app/fnpack"
      - "/var/apps:/app/apps"
      - "/${TRIM_APPDEST_VOL}:/${TRIM_APPDEST_VOL}"
    environment:
      - FNOS_HTTP_PORT=${wizard_fnos_http_port}