services:
  fnpackup:
    image: snltty/fnpackup
    container_name: fnpackup
    privileged: true
    network_mode: host
    restart: always
    tty: true
    stdin_open: true
    volumes:
      - "/$TRIM_APPDEST_VOL/@appshare/fnpackup-docker/projects:/app/projects"
      - "/$TRIM_APPDEST_VOL/@appshare/fnpackup-docker/statics:/app/statics"
      - "/usr/local/bin/appcenter-cli:/app/appcenter-cli:ro"
      - "/usr/local/bin/fnpack:/app/fnpack:ro"
      - "/var/apps:/app/apps:ro"